apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-thymeleaf-master
spec:
  selector:
    matchLabels:
      app: spring-boot-thymeleaf
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-thymeleaf
    spec:
      containers:
        - name: spring-form
          image: spring-form # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9595 # The port that the container is running on in the cluster
